
"use client";

import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { User, Shield, GraduationCap } from "lucide-react";
import { useAuth, useFirestore } from "@/firebase";
import { signInAnonymously } from "firebase/auth";
import { doc, setDoc } from "firebase/firestore";

const userProfiles = {
    admin: { uid: 'admin_user', name: 'Dr. Evelyn Reed', role: 'admin', email: 'e.reed@umma.ac.ke', avatar: 'admin_avatar' },
    lecturer: { uid: 'lecturer_user', name: 'Prof. Samuel Miles', role: 'lecturer', email: 's.miles@umma.ac.ke', avatar: 'lecturer_avatar' },
    student: { uid: 'student_user', name: 'Aisha Juma', role: 'student', email: 'a.juma@student.umma.ac.ke', avatar: 'student_avatar' }
}

export default function LoginForm() {
  const router = useRouter();
  const auth = useAuth();
  const firestore = useFirestore();

  const handleLogin = async (role: 'admin' | 'lecturer' | 'student') => {
    try {
      // Sign in anonymously first
      const userCredential = await signInAnonymously(auth);
      const user = userCredential.user;

      if (user && firestore) {
        // This is not secure for a real app, but for demo purposes, we'll overwrite the UID
        // with our mock user's UID to maintain consistency across logins.
        const profileData = userProfiles[role];
        const userDocRef = doc(firestore, "users", profileData.uid);
        
        // We use setDoc to create or update the user's profile document.
        // This effectively "assigns" the role and profile to the anonymous session.
        await setDoc(userDocRef, profileData, { merge: true });

        // A more secure approach for a real app would be to use a custom token
        // generated by a backend that contains the user's role as a claim.
        // For this demo, we'll re-authenticate with a custom token that the emulator
        // is configured to accept. This gives us a consistent UID for each role.
        const mockToken = `{"uid": "${profileData.uid}"}`;
        const finalUserCredential = await auth.signInWithCustomToken(mockToken);

        if(finalUserCredential) {
            router.push('/dashboard');
        }
      }
    } catch (error) {
      console.error("Authentication failed:", error);
    }
  };

  return (
    <div className="space-y-4">
      <Button
        onClick={() => handleLogin('admin')}
        className="w-full"
        variant="outline"
      >
        <Shield className="mr-2 h-4 w-4" />
        Sign in as Administrator
      </Button>
      <Button
        onClick={() => handleLogin('lecturer')}
        className="w-full"
        variant="outline"
      >
        <User className="mr-2 h-4 w-4" />
        Sign in as Lecturer
      </Button>
      <Button
        onClick={() => handleLogin('student')}
        className="w-full"
      >
        <GraduationCap className="mr-2 h-4 w-4" />
        Sign in as Student
      </Button>
    </div>
  );
}
