
"use client";

import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { User, Shield, GraduationCap } from "lucide-react";
import { useAuth, useFirestore } from "@/firebase";
import { signInWithCustomToken } from "firebase/auth";
import { doc, setDoc } from "firebase/firestore";


// In a real app, you'd get these tokens from a secure backend after a login process.
// For this demo, we'll use mock custom tokens that the emulator will accept.
const mockCustomTokens = {
    admin: '{"uid": "admin_user"}',
    lecturer: '{"uid": "lecturer_user"}',
    student: '{"uid": "student_user"}'
}

const userProfiles = {
    admin: { uid: 'admin_user', name: 'Dr. Evelyn Reed', role: 'admin', email: 'e.reed@umma.ac.ke', avatar: 'admin_avatar' },
    lecturer: { uid: 'lecturer_user', name: 'Prof. Samuel Miles', role: 'lecturer', email: 's.miles@umma.ac.ke', avatar: 'lecturer_avatar' },
    student: { uid: 'student_user', name: 'Aisha Juma', role: 'student', email: 'a.juma@student.umma.ac.ke', avatar: 'student_avatar' }
}

export default function LoginForm() {
  const router = useRouter();
  const auth = useAuth();
  const firestore = useFirestore();

  const handleLogin = async (role: 'admin' | 'lecturer' | 'student') => {
    try {
      // For this demo, we use placeholder tokens. In a real app, these would be generated by a secure backend.
      // Firebase Auth is configured to accept these tokens for this demo project.
      const userCredential = await signInWithCustomToken(auth, mockCustomTokens[role]);
      const user = userCredential.user;

      if (user && firestore) {
        const userDocRef = doc(firestore, "users", user.uid);
        // We use setDoc with merge:true to create or update the user's profile document.
        await setDoc(userDocRef, userProfiles[role], { merge: true });
      }

      router.push('/dashboard');
    } catch (error) {
      console.error("Custom sign-in failed:", error);
    }
  };

  return (
    <div className="space-y-4">
      <Button
        onClick={() => handleLogin('admin')}
        className="w-full"
        variant="outline"
      >
        <Shield className="mr-2 h-4 w-4" />
        Sign in as Administrator
      </Button>
      <Button
        onClick={() => handleLogin('lecturer')}
        className="w-full"
        variant="outline"
      >
        <User className="mr-2 h-4 w-4" />
        Sign in as Lecturer
      </Button>
      <Button
        onClick={() => handleLogin('student')}
        className="w-full"
      >
        <GraduationCap className="mr-2 h-4 w-4" />
        Sign in as Student
      </Button>
    </div>
  );
}
